// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensorIngestion.Infrastructure.Persistence;

#nullable disable

namespace SensorIngestion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SensorIngestionDbContext))]
    partial class SensorIngestionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SensorIngestion.Domain.Entities.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DbEntryDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EndTs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PeakValue")
                        .HasColumnType("REAL");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartTs")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleId", "DeviceId", "Metric", "StartTs")
                        .IsUnique()
                        .HasDatabaseName("IX_Alert_NaturalKey");

                    b.ToTable("Alert", (string)null);
                });

            modelBuilder.Entity("SensorIngestion.Domain.Entities.ReadingViolation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DbEntryDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("ReadingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("IX_ReadingViolation_RuleId");

                    b.HasIndex("ReadingId", "RuleId")
                        .IsUnique()
                        .HasDatabaseName("IX_ReadingViolation_Reading_Rule");

                    b.ToTable("ReadingViolation", (string)null);
                });

            modelBuilder.Entity("SensorIngestion.Domain.Entities.Rule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DbEntryDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Operator")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Threshold")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RuleId")
                        .IsUnique()
                        .HasDatabaseName("IX_Rule_RuleId");

                    b.ToTable("Rule", (string)null);
                });

            modelBuilder.Entity("SensorIngestion.Domain.Entities.SensorReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Classification")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DbEntryDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Metric", "Timestamp", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_Reading_NaturalKey");

                    b.ToTable("SensorReading", (string)null);
                });

            modelBuilder.Entity("SensorIngestion.Domain.Entities.ReadingViolation", b =>
                {
                    b.HasOne("SensorIngestion.Domain.Entities.SensorReading", "Reading")
                        .WithMany("Violations")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("SensorIngestion.Domain.Entities.SensorReading", b =>
                {
                    b.Navigation("Violations");
                });
#pragma warning restore 612, 618
        }
    }
}
